# -*- coding: utf-8 -*-
"""autocomplete_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWHX6D1b6plaKB9PyenQWJdUelKxCNms
"""

# install HuggingFace 'datasets'
!pip install datasets

# load wikitext from datasets
# using wikitext2 raw version

from datasets import load_dataset

dataset = load_dataset("wikitext", "wikitext-2-raw-v1")
print(dataset)

# total rows and non-empty rows dont match here
# need to do some cleaning
count_nonempty = 0
count_total = 0

for entry in dataset["train"]:
    count_total += 1
    if entry["text"].strip() != "":
        count_nonempty += 1

print("Total rows:", count_total)
print("Non-empty rows:", count_nonempty)

# remove blank lines
dataset = dataset.filter(lambda x: x["text"].strip() != "")

# checking what data looks like
print(dataset["train"][0])

# now the row numbers match
count_nonempty = 0
count_total = 0

for entry in dataset["train"]:
    count_total += 1
    if entry["text"].strip() != "":
        count_nonempty += 1

print("Total rows:", count_total)
print("Non-empty rows:", count_nonempty)

# PRE-PROCESSING
# 're' for regex
# this function extracts and cleans text
# note to self: wikitext2 is about 2M words
# this counts about 1.75M
import re

def preprocess(text):
    text = text.lower()
    return re.findall(r'\b\w+\b', text)

# building the corpus
all_words = []

for entry in dataset["train"]:
    text = entry["text"]
    if text.strip():   # simple safe guard
        all_words.extend(preprocess(text))

print("Total words:", len(all_words))

# build word frequency
#count unique words and most frequent words
from collections import Counter

word_freq = Counter(all_words)

print("Unique words:", len(word_freq))
print(word_freq.most_common(10))

# function to do prefix based matching for suggestions
# return top 5 suggestions
def get_suggestions(prefix, word_freq, k=5):
    prefix = prefix.lower()

    matches = [word for word in word_freq if word.startswith(prefix)]

    ranked = sorted(matches, key=lambda w: word_freq[w], reverse=True)

    return ranked[:k]

# sanity check
# testing suggestions for "comp" and "auto"
print(get_suggestions("comp", word_freq))
print(get_suggestions("auto", word_freq))

# sanity check
# testing suggestions for "a" and "b"
print(get_suggestions("a", word_freq))
print(get_suggestions("b", word_freq))

def autocomplete(prefix, word_freq, k=5):
    prefix = prefix.lower()

    # Find matching words
    matches = [word for word in word_freq if word.startswith(prefix)]

    # Rank by frequency
    matches = sorted(matches, key=lambda w: word_freq[w], reverse=True)

    return matches[:k]

# sanity check
# test the autocomplete function
print(autocomplete("comp", word_freq))
print(autocomplete("auto", word_freq))
print(autocomplete("data", word_freq))

# make a random sample of 1000 words from the dataset
# print the first 10 just to check
import random

sample = random.sample(list(word_freq.keys()), 1000)
print(sample[:10])

# EXPERIMENT STARTS HERE
def keystroke_savings_real(word, word_counts, k=5):
    for i in range(1, len(word)):
        prefix = word[:i]
        suggestions = autocomplete(prefix, word_counts, k)

        if word in suggestions:
            # user would stop typing here
            return len(word) - i

    # never predicted
    return 0

def average_keystroke_savings_real(sample, word_counts, k=5):
    total = 0

    for word in sample:
        if len(word) < 3:
            continue
        total += keystroke_savings_real(word, word_counts, k)

    return total / len(sample)

def top_k_accuracy_real(sample, word_counts, k=5):
    correct = 0
    total = 0

    for word in sample:
        found = False

        for i in range(1, len(word)):
            prefix = word[:i]
            suggestions = autocomplete(prefix, word_counts, k)

            if word in suggestions:
                correct += 1
                found = True
                break

        total += 1

    return correct / total

accuracy = top_k_accuracy_real(sample, word_freq, k=5)
keystrokes = average_keystroke_savings_real(sample, word_freq, k=5)

print(f"Top-5 Accuracy: {accuracy:.4f}")
print(f"Average Keystroke Savings: {keystrokes:.2f}")

# simulate someone typing by iterating through a word
prefix = "c"
word = "dictionary"
for i in range(1, len(word) + 1):
    current = word[:i]
    print(f"Input: {current}")
    print("Suggestions:", autocomplete(current, word_freq))
    print()

# run the experiment 5 times

results = []

for _ in range(5):
    sample = random.sample(list(word_freq.keys()), 1000)

    acc = top_k_accuracy_real(sample, word_freq)
    ks = average_keystroke_savings_real(sample, word_freq)

    results.append((acc, ks))

avg_acc = sum(r[0] for r in results) / len(results)
avg_ks = sum(r[1] for r in results) / len(results)

print(f"Average Accuracy over runs: {avg_acc:.4f}")
print(f"Average Keystroke Savings: {avg_ks:.2f}")

